/**
 * Unit tests for the Markdown Generator
 *
 * Tests the generateDailyLog function with various commit scenarios.
 * Created by Agent 3.
 */

import { describe, it, expect } from 'vitest'
import { generateDailyLog } from '../src/generator.js'
import type { Commit } from '../src/types.js'

describe('generateDailyLog', () => {
  it('should generate a daily log with zero commits', () => {
    const commits: Commit[] = []
    const result = generateDailyLog(commits)

    // Should contain basic structure
    expect(result).toContain('# Daily Log')
    expect(result).toContain('## Session Info')
    expect(result).toContain('Duration: N/A')
    expect(result).toContain('Focus Area: No activity')
    expect(result).toContain('## Work Completed')
    expect(result).toContain('## Code Changes')
    expect(result).toContain('## Commits')
    expect(result).toContain('## Generated by git-to-daily')
  })

  it('should generate a daily log with a single commit', () => {
    const commits: Commit[] = [
      {
        hash: 'abc123def456',
        message: 'feat: add user authentication',
        author: 'Test Developer',
        timestamp: new Date('2026-01-31T10:30:00Z'),
        files: [
          { path: 'src/auth.ts', status: 'added' },
          { path: 'src/utils.ts', status: 'modified' },
        ],
      },
    ]

    const result = generateDailyLog(commits)

    // Check header
    expect(result).toContain('# Daily Log - 2026-01-31')

    // Check session info
    expect(result).toContain('Duration: Single commit')
    expect(result).toContain('Focus Area: Feature development')

    // Check work completed
    expect(result).toContain('feat: add user authentication')

    // Check code changes
    expect(result).toContain('src/auth.ts')
    expect(result).toContain('src/utils.ts')
    expect(result).toContain('➕') // added emoji
    expect(result).toContain('✏️') // modified emoji

    // Check commit log
    expect(result).toContain('Hash: `abc123d`')
    expect(result).toContain('Author: Test Developer')
    expect(result).toContain('Files changed: 2')
  })

  it('should generate a daily log with multiple commits', () => {
    const commits: Commit[] = [
      {
        hash: 'commit1hash',
        message: 'fix: resolve login bug',
        author: 'Developer 1',
        timestamp: new Date('2026-01-31T09:00:00Z'),
        files: [{ path: 'src/auth.ts', status: 'modified' }],
      },
      {
        hash: 'commit2hash',
        message: 'refactor: clean up code',
        author: 'Developer 2',
        timestamp: new Date('2026-01-31T11:30:00Z'),
        files: [{ path: 'src/utils.ts', status: 'modified' }],
      },
    ]

    const result = generateDailyLog(commits)

    // Check both commits are listed
    expect(result).toContain('fix: resolve login bug')
    expect(result).toContain('refactor: clean up code')

    // Check duration calculation (2.5 hours)
    expect(result).toContain('2h 30m')

    // Check focus area inference (should detect refactoring)
    expect(result).toContain('Focus Area: Refactoring')
  })

  it('should calculate duration correctly for commits less than an hour apart', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'commit 1',
        author: 'Dev',
        timestamp: new Date('2026-01-31T10:00:00Z'),
        files: [],
      },
      {
        hash: 'hash2',
        message: 'commit 2',
        author: 'Dev',
        timestamp: new Date('2026-01-31T10:45:00Z'),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)

    // Should show only minutes
    expect(result).toContain('45m')
    expect(result).not.toContain('0h')
  })

  it('should infer "Feature development" focus area from commit messages', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'feat: new feature',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Focus Area: Feature development')
  })

  it('should infer "Bug fixes" focus area from commit messages', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'fix: critical bug',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Focus Area: Bug fixes')
  })

  it('should infer "Testing" focus area from commit messages', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'test: add unit tests',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Focus Area: Testing')
  })

  it('should infer "Documentation" focus area from commit messages', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'docs: update README',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Focus Area: Documentation')
  })

  it('should default to "Development" for generic commits', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'update code',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Focus Area: Development')
  })

  it('should use correct emoji for added files', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'add files',
        author: 'Dev',
        timestamp: new Date(),
        files: [{ path: 'newfile.ts', status: 'added' }],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('➕')
  })

  it('should use correct emoji for modified files', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'modify files',
        author: 'Dev',
        timestamp: new Date(),
        files: [{ path: 'existingfile.ts', status: 'modified' }],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('✏️')
  })

  it('should use correct emoji for deleted files', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'remove files',
        author: 'Dev',
        timestamp: new Date(),
        files: [{ path: 'oldfile.ts', status: 'deleted' }],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('🗑️')
  })

  it('should handle multiple commits modifying the same file', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'first change',
        author: 'Dev',
        timestamp: new Date('2026-01-31T10:00:00Z'),
        files: [{ path: 'same-file.ts', status: 'added' }],
      },
      {
        hash: 'hash2',
        message: 'second change',
        author: 'Dev',
        timestamp: new Date('2026-01-31T11:00:00Z'),
        files: [{ path: 'same-file.ts', status: 'modified' }],
      },
    ]

    const result = generateDailyLog(commits)

    // File should only appear once in Code Changes section
    const codeChangesSection = result.split('## Code Changes')[1].split('## Commits')[0]
    const fileOccurrences = (codeChangesSection.match(/same-file\.ts/g) || []).length
    expect(fileOccurrences).toBe(1)
  })

  it('should format timestamps correctly', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'test commit',
        author: 'Dev',
        timestamp: new Date('2026-01-31T14:30:00Z'),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)

    // Should format time as HH:MM (24-hour format)
    expect(result).toMatch(/\d{2}:\d{2}/)
  })

  it('should truncate commit hash to 7 characters', () => {
    const commits: Commit[] = [
      {
        hash: 'abcdef1234567890',
        message: 'test',
        author: 'Dev',
        timestamp: new Date(),
        files: [],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Hash: `abcdef1`')
  })

  it('should include file count in commit log', () => {
    const commits: Commit[] = [
      {
        hash: 'hash1',
        message: 'test',
        author: 'Dev',
        timestamp: new Date(),
        files: [
          { path: 'file1.ts', status: 'added' },
          { path: 'file2.ts', status: 'modified' },
          { path: 'file3.ts', status: 'deleted' },
        ],
      },
    ]

    const result = generateDailyLog(commits)
    expect(result).toContain('Files changed: 3')
  })
})
