/**
 * Markdown Generator Module
 *
 * Formats git commit data into Obsidian Daily Log format.
 * Created by Agent 1.
 */

import type { Commit, FileChange } from './types.js'

/**
 * Generates a Daily Log markdown document from commits
 *
 * @param commits - Array of commits to include in the log
 * @returns Formatted markdown string
 */
export function generateDailyLog(commits: Commit[]): string {
  const date = formatDate(new Date())
  const duration = calculateDuration(commits)
  const focusArea = inferFocusArea(commits)

  const sections = [
    generateHeader(date),
    generateSessionInfo(date, duration, focusArea),
    generateWorkCompleted(commits),
    generateCodeChanges(commits),
    generateCommitLog(commits),
    generateFooter(),
  ]

  return sections.join('\n\n')
}

/**
 * Generates the header section
 */
function generateHeader(date: string): string {
  return `# Daily Log - ${date}`
}

/**
 * Generates the session info section
 */
function generateSessionInfo(date: string, duration: string, focusArea: string): string {
  return [
    '## Session Info',
    `- **Date**: ${date}`,
    `- **Duration**: ${duration}`,
    `- **Focus Area**: ${focusArea}`,
  ].join('\n')
}

/**
 * Generates the work completed section with task checkboxes
 */
function generateWorkCompleted(commits: Commit[]): string {
  const tasks = commits.map((commit) => `- ✅ ${commit.message}`)

  return ['## Work Completed', '### Tasks', ...tasks].join('\n')
}

/**
 * Generates the code changes section showing modified files
 */
function generateCodeChanges(commits: Commit[]): string {
  // Build a map of file paths to their commits
  const fileMap = new Map<string, { commit: Commit; status: FileChange['status'] }>()

  for (const commit of commits) {
    for (const file of commit.files) {
      // Keep the most recent change for each file
      if (!fileMap.has(file.path)) {
        fileMap.set(file.path, { commit, status: file.status })
      }
    }
  }

  const fileEntries = Array.from(fileMap.entries()).map(([path, { commit, status }]) => {
    const statusEmoji = getStatusEmoji(status)
    return `  - ${statusEmoji} \`${path}\` - ${commit.message}`
  })

  return ['## Code Changes', '### Files Modified', ...fileEntries].join('\n')
}

/**
 * Generates the commit log section with detailed commit information
 */
function generateCommitLog(commits: Commit[]): string {
  const commitEntries = commits.map((commit) => {
    const timestamp = formatTime(commit.timestamp)
    const fileCount = commit.files.length
    return [
      `**${timestamp}** - ${commit.message}`,
      `- Hash: \`${commit.hash.substring(0, 7)}\``,
      `- Author: ${commit.author}`,
      `- Files changed: ${fileCount}`,
    ].join('\n')
  })

  return ['## Commits', '```', ...commitEntries, '```'].join('\n')
}

/**
 * Generates the footer
 */
function generateFooter(): string {
  return [
    '---',
    '',
    '## Generated by git-to-daily',
    'This log was automatically generated from git commits.',
  ].join('\n')
}

/**
 * Formats a date as YYYY-MM-DD
 */
function formatDate(date: Date): string {
  return date.toISOString().split('T')[0]
}

/**
 * Formats a time as HH:MM
 */
function formatTime(date: Date): string {
  return date.toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  })
}

/**
 * Calculates session duration from commit timestamps
 */
function calculateDuration(commits: Commit[]): string {
  if (commits.length === 0) {
    return 'N/A'
  }

  if (commits.length === 1) {
    return 'Single commit'
  }

  const timestamps = commits.map((c) => c.timestamp.getTime())
  const earliest = Math.min(...timestamps)
  const latest = Math.max(...timestamps)
  const durationMs = latest - earliest

  const hours = Math.floor(durationMs / (1000 * 60 * 60))
  const minutes = Math.floor((durationMs % (1000 * 60 * 60)) / (1000 * 60))

  if (hours > 0) {
    return `${hours}h ${minutes}m`
  }
  return `${minutes}m`
}

/**
 * Infers focus area from commit messages
 */
function inferFocusArea(commits: Commit[]): string {
  if (commits.length === 0) {
    return 'No activity'
  }

  // Extract common keywords from commit messages
  const messages = commits.map((c) => c.message.toLowerCase())

  // Check for common patterns
  if (messages.some((m) => m.includes('feat') || m.includes('feature'))) {
    return 'Feature development'
  }
  if (messages.some((m) => m.includes('fix') || m.includes('bug'))) {
    return 'Bug fixes'
  }
  if (messages.some((m) => m.includes('refactor'))) {
    return 'Refactoring'
  }
  if (messages.some((m) => m.includes('test'))) {
    return 'Testing'
  }
  if (messages.some((m) => m.includes('doc'))) {
    return 'Documentation'
  }

  // Default to general development
  return 'Development'
}

/**
 * Gets an emoji for file status
 */
function getStatusEmoji(status: FileChange['status']): string {
  switch (status) {
    case 'added':
      return '➕'
    case 'modified':
      return '✏️'
    case 'deleted':
      return '🗑️'
    default:
      return '📝'
  }
}
